### ISSUE TITLE
New release (Melodic + Noetic)

### ISSUE THREAD

**Issue by peci1** [ros-infrastructure/rosdoc_lite#104]
@jack-oquin This package hasn't seen a release for quite some time. Especially on Melodic, where the latest version is 0.2.9 tagged in Jan '19. There were some crucial fixes in the meantime (e.g. external docs URL) which still can't be used on Melodic. Given the Melodic EOL closing in, it would be great to give people the possibility to leave their docs in a good shape :)

Before making the release, please consider merging #103. It would really help fixing wrong behavior of Doxygen on correct code.

**Comment by peci1** [comment]
@tfoote Melodic is passe, but Noetic would really make use of the new features commited since the last release 3 years ago.

**Comment by tfoote** [comment]
In general we use rosdoc_lite from tip for deployment and don't release often. But here's a release: https://github.com/ros/rosdistro/pull/38464

**Comment by peci1** [comment]
Thanks!

> In general we use rosdoc_lite from tip for deployment

What does this mean? Does the (ROS1) buildfarm use the tip and not the released package?

**Comment by peci1** [comment]
I've documented the new options on http://wiki.ros.org/rosdoc_lite .

**Comment by tfoote** [comment]
> What does this mean? Does the (ROS1) buildfarm use the tip and not the released package?

Yes

**Comment by peci1** [comment]
Indeed: https://github.com/ros-infrastructure/ros_buildfarm/blob/7237125ef424efef26cf3419ab7ab4063f97aea5/ros_buildfarm/templates/doc/doc_job.xml.em#L93 .

Thanks, haven't known that!

The same holds for catkin-sphinx, too.
