### ISSUE TITLE
"Edit on Github" link for appropriate sphynix pages

### ISSUE THREAD

**Issue by davetcoleman** [ros-infrastructure/rosdoc_lite#53]
This would be a really nice feature for encouraging ROS users to help with documentation. Similar to readthedocs we could have a plugin that provides a link at the top of sphinx pages:

![screen shot 2014-12-03 at 5 54 00 pm](https://cloud.githubusercontent.com/assets/561060/5292344/70e5bc26-7b15-11e4-8f33-f044a77f3e89.png)

What are your guys thoughts on this? Is this even the correct repo for this issue? I don't know much about using Sphinx documentation but this feature is badly needed IMHO. Inline docs is how MoveIt! developers have chosen to do documentation (no more wiki) and the result has been there have been no further outside documentation contributions. 

A quick google search led me to this:
https://mg.pov.lt/blog/sphinx-edit-on-github.html

But I think I would have to learn a lot more about this stuff before I could figure out how to contribute a patch and am hoping someone else could.

Thoughts?

**Comment by jack-oquin** [comment]
I have very little idea how to do this myself, but would be happy to merge an applicable pull request.

**Comment by davetcoleman** [comment]
I've achieved this by copying http://docs.fetchrobotics.com/ who in turn copied ReadTheDocs's theme for Sphinx. My implementation:

https://github.com/ros-planning/moveit_tutorials/blob/8d1498956b4e92e5e9a71e61becb04ae34c27661/_themes/sphinx_rtd_theme/breadcrumbs.html#L11
