### ISSUE TITLE
Is search form available in codeapi page?

### ISSUE THREAD

**Issue by wkentaro** [ros-infrastructure/rosdoc_lite#56]
I'm adding code api reference at docs.ros.org/api.
But there is no search form (like basic sphinx page).
Are there any way to add search form at codeapi page?

**Comment by wkentaro** [comment]
How can I make the option `SEARCHENGINE = YES` ?
https://github.com/ros-infrastructure/rosdoc_lite/blob/master/src/rosdoc_lite/templates/doxy.template#L1469

**Comment by jack-oquin** [comment]
That does not appear to be [one of the doxygen variables that a package can override](https://github.com/ros-infrastructure/rosdoc_lite/blob/master/src/rosdoc_lite/doxygenator.py#L176).

If you'd like to submit and test a pull request adding it, I'll be happy to review and merge it. If you do, please alphabetize that dvars dictionary, so it will be easier to see what's there and what's not.

**Comment by wkentaro** [comment]
Thanks. I tried in my local and the form appears.
![image](https://cloud.githubusercontent.com/assets/4310419/9476425/a4745558-4ba7-11e5-9647-adcb66a4d7dd.png)

If I the master branch on github.com is updated, is the documents on docs.ros.org is updated?
Or should I wait for some releases?

**Comment by wkentaro** [comment]
(If possible) I'd like to use sever side search for full text search, is that possible using docs.ros.org?

**Comment by jack-oquin** [comment]
I believe the build farm always checks out the master branch and uses the latest version.

I normally make a new release for the active ROS distributions (currently Indigo and Jade), so people running rosdoc-lite locally will get an up-to-date copy.

Does f6d56b3 solve your problem?

> (If possible) I'd like to use sever side search for full text search, is that possible using docs.ros.org?

I don't know what server side search means, and can't answer that part of your question.
