### ISSUE TITLE
What version is rosdoc using for Sphinx?

### ISSUE THREAD

**Issue by davetcoleman** [ros-infrastructure/rosdoc_lite#69]
Is it the default version available in Ubuntu for the corresponding ROS distro? I just ran into a problem where ReadTheDocs theme uses Sphinx features in 1.3 (the [caption](http://www.sphinx-doc.org/en/stable/markup/toctree.html) in TOC) but the buildfarm uses on older version in indigo ([output](http://build.ros.org/job/Idoc__moveit_tutorials__ubuntu_trusty_amd64/lastBuild/console))

**Comment by tfoote** [comment]
Doc builds are done on the LTS associated with the rosdistro defined in the ros_buildfarm_config such as: 

- [Indigo](https://github.com/ros-infrastructure/ros_buildfarm_config/blob/master/indigo/doc-build.yaml#L48-L51)
- [Kinetic](https://github.com/ros-infrastructure/ros_buildfarm_config/blob/master/kinetic/doc-build.yaml#L48-L51)


From the job logs I see:
```
22:13:03   RUN echo "python-sphinx: 1.2.2+dfsg-1ubuntu1.1" && python3 -u /tmp/wrapper_scripts/apt.py update-install-clean -q -y -o Debug::pkgProblemResolver=yes python-sphinx
```
