### ISSUE TITLE
python-catkin-pkg 0.3.4-1 broke indigo branch of rosdoc_lite

### ISSUE THREAD

**Issue by jdcarpinelli** [ros-infrastructure/rosdoc_lite#75]
The new python-catkin-pkg package seems to leave out a "parse_package" function from packages.py. Running rosdoc_lite using the python-catkin-pkg and python-catkin-modules version 0.3.1-1 produces correct resutls, while running rosdoc_lite using the new 0.3.4-1 version of those two packages yields...
`Traceback (most recent call last):
  File "/opt/ros/indigo/bin/rosdoc_lite", line 37, in <module>
    rosdoc_lite.main()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rosdoc_lite/__init__.py", line 225, in main
    pkg_desc = get_pkg_desc(path)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rosdoc_lite/__init__.py", line 241, in get_pkg_desc
    pkg_desc = packages.parse_package(path)
AttributeError: 'module' object has no attribute 'parse_package'
`

**Comment by mikepurvis** [comment]
@dirk-thomas More fallout from the multiprocessing change (sorry, gah). Would you like me to add back a shim function to `catkin_pkg`, or update `rosdoc_lite`?

**Comment by dirk-thomas** [comment]
This has already been fixed ten days ago: #74

**Comment by jdcarpinelli** [comment]
Sorry I missed revision 74, thank you!

**Comment by dirk-thomas** [comment]
I guess I will have to roll new releases for Indigo, Jade, and Kinetic since I assume you installed the Debian package?

**Comment by jdcarpinelli** [comment]
That would be great, thanks. I installed via apt: `apt-get install ros-indigo-rosdoc-lite`

**Comment by dirk-thomas** [comment]
On the way: ros/rosdistro#15146
