### ISSUE TITLE
Add qhelpgenerator option.

### ISSUE THREAD

**Issue by Levi-Armstrong** [ros-infrastructure/rosdoc_lite#77]
Hello, 

I currently maintain the ROS Qt Creator plug-in and I would like to incorporate all of the ros documentation. To accomplish this I need to configure a few doxygen flags. The only parameter that would need to be exposed would be GENERATE_QHP the others would be a function of the package name. I would also be interested in adding another option flag for generating this without having to modify each package .yaml file. I would create a pull request if you are ok with the additional functionality. 

GENERATE_QHP = YES/NO 
QCH_FILE = <package_name>.qch
QHP_NAMESPACE = org.ros.<package_name>

**Comment by jack-oquin** [comment]
Yes, a pull request would be very helpful.

**Comment by Levi-Armstrong** [comment]
Just created a PR #78 .

**Comment by Levi-Armstrong** [comment]
PR #78 was merged
