### ISSUE TITLE
Release for melodic

### ISSUE THREAD

**Issue by hrnr** [ros-infrastructure/rosdoc_lite#81]
rosdoc_lite needs release for melodic.

**Comment by hrnr** [comment]
I have also noticed that doxygen documentation generated for melodic is missing the top navigation bar. Is this desired? IMHO it makes navigation much harder.

See http://docs.ros.org/melodic/api/tf2_ros/html/c++/ vs http://docs.ros.org/lunar/api/tf2_ros/html/c++/

**Comment by hrnr** [comment]
fixed in #82

**Comment by nowittyusername** [comment]
Hi!

Is there any plans to release rosdoc_lite to melodic in the near future?

**Comment by tfoote** [comment]
https://github.com/ros/rosdistro/pull/18745

**Comment by hrnr** [comment]
Great! Could we also get a new release (0.2.8?), with #82 included? Right now rosdoc_lite is pretty unusable for doxygen docs on Melodic.

**Comment by tfoote** [comment]
In general we usually run rosdoc_lite from source but I've released 0.2.8 into melodic: https://github.com/ros/rosdistro/pull/19138
