### ISSUE TITLE
Drop epydoc support in ROS Noetic?

### ISSUE THREAD

**Issue by sloretz** [ros-infrastructure/rosdoc_lite#92]
It looks like epydoc is not released into Ubuntu Focal, and [does not support Python 3](https://sourceforge.net/p/epydoc/feature-requests/98/). Maybe `rosdoc_lite` should drop epydoc support in ROS Noetic?

**Comment by tfoote** [comment]
Well that's a pain but I think we'll have to do that as we don't have the bandwidth to make that port for them.

**Comment by mikepurvis** [comment]
We're switching to pydoctor. It's not identical, but fills a similar role in terms of auto-documentation of Python modules.

See discussion: https://github.com/mikepurvis/catkin_tools_document/pull/10#pullrequestreview-310670818
