### ISSUE TITLE
Broken link on wiki.ros.org

### ISSUE THREAD

**Issue by standmit** [ros-infrastructure/rosdoc_lite#94]
Broken link in [paragraph 2.4](http://wiki.ros.org/rosdoc_lite#A.28Option.29_Using_Doxygen_Tag_Files)
>For more information on using tag files with Doxygen to link to external documentation, see this [page](http://www.stack.nl/~dimitri/doxygen/external.html).

**Comment by tfoote** [comment]
I think this is the equivalent page: https://www.stack.nl/~dimitri/doxygen/external.html 

Wiki page updated. In the future the wiki is community editable.
