### ISSUE TITLE
Doxygen for ROS2

### ISSUE THREAD

**Issue by JaehyunShim** [ros-infrastructure/rosdoc_lite#99]
Hi,  

I am trying to find a way to use rosdoc_lite like features for ROS2 projects.
rosdoc_lite seems to support only ROS1 versions.
Any advice or suggestions? 

Thank you in advance, 
Ryan

**Comment by tfoote** [comment]
We are not planning to port rosdoc_lite to ROS 2. Please see: https://discourse.ros.org/t/request-for-comment-per-package-documentation-requirements/16699/2 for more info relating to ROS 2.
